"""
ML Strategy Engine for automated algorithm, search, and hardware recommendation.
Implements Stage 5 ML Strategy Engine with deterministic safety fallbacks.

v2: covers every problem class (LP, MILP, QP, MIQP), chooses between the QP interior point
and active-set solvers, and recommends cutting-plane and heuristic intensity for MILP.
The recommendation is advisory: the dispatcher enforces algorithm / problem-class compatibility
and the independent validator certifies every result.
"""
from dataclasses import dataclass, field
from typing import Dict, Optional
import numpy as np

from sovereign_opt.model.model import OptimizationModel
from sovereign_opt.presolve.presolver import PresolveStats
from sovereign_opt.ml.features import FeatureExtractor


@dataclass
class StrategyRecommendation:
    """
    Recommended solving strategy generated by the ML Strategy Engine.
    """
    recommended_algorithm: str  # 'simplex', 'dual_simplex', 'interior_point', 'branch_and_bound', 'active_set', 'qp_interior_point'
    algorithm_probabilities: Dict[str, float]
    confidence_score: float
    recommended_hardware: str  # 'cpu', 'gpu', 'hybrid'
    branching_strategy: str  # 'reliability_pseudocost', 'none'
    feature_attributions: Dict[str, float] = field(default_factory=dict)
    deterministic_fallback: str = "simplex"
    cut_strategy: str = "none"  # 'none', 'moderate', 'aggressive'
    heuristic_intensity: str = "none"  # 'none', 'light', 'full'
    relaxation_solver: Optional[str] = None


def _sigmoid(v: float) -> float:
    return float(1.0 / (1.0 + np.exp(-v)))


_SELECTOR_CACHE: Dict[str, object] = {}


def _learned_lp_choice(features: Dict[str, float]):
    """Apply the selector trained by benchmarks/train_selector.py (sovereign_opt/ml/lp_selector.json)."""
    import json
    import os
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lp_selector.json")
    if "model" not in _SELECTOR_CACHE:
        try:
            with open(path) as f:
                _SELECTOR_CACHE["model"] = json.load(f)
        except (OSError, ValueError):
            _SELECTOR_CACHE["model"] = None
    sel = _SELECTOR_CACHE["model"]
    if not sel:
        return None
    try:
        x = (np.array([features[k] for k in sel["features"]]) - np.array(sel["mean"])) / np.array(sel["std"])
        z = np.array(sel["weights"]) @ np.append(x, 1.0)
        p = np.exp(z - z.max())
        p /= p.sum()
    except (KeyError, ValueError):
        return None
    j = int(np.argmax(p))
    return {a: float(v) for a, v in zip(sel["algorithms"], p)}, sel["algorithms"][j], float(p[j])


class MLStrategyEngine:
    """
    Local, sovereign ML strategy model.
    Offline inference without LLM, internet, or third-party dependencies.
    """

    def __init__(self, confidence_threshold: float = 0.55):
        self.confidence_threshold = confidence_threshold

    def recommend(
        self, model: OptimizationModel, presolve_stats: Optional[PresolveStats] = None
    ) -> StrategyRecommendation:
        features = FeatureExtractor.extract(model, presolve_stats)
        p_class = model.classify()
        attributions: Dict[str, float] = {}
        cut_strategy, heuristic_intensity, relaxation = "none", "none", None
        branching = "none"

        if p_class in ("MILP", "MIQP"):
            rec_algo = "branch_and_bound"
            algo_probs = {"branch_and_bound": 1.0}
            confidence = 1.0
            fallback = "branch_and_bound"
            branching = "reliability_pseudocost"
            relaxation = "dual_simplex" if p_class == "MILP" else "qp_interior_point"
            binary_share = features["frac_binary"] / max(features["frac_integer"] + features["frac_binary"], 1e-9)
            # Cuts pay off most on binary-heavy, tightly constrained models.
            cut_score = 1.2 * binary_share + 0.6 * features["frac_le_cons"] - 0.25 * features["log_num_cons"]
            cut_strategy = "none" if p_class == "MIQP" else ("aggressive" if cut_score > 0.9 else "moderate")
            heuristic_intensity = "full" if features["log_num_vars"] > 1.5 else "light"
            attributions["integer_variable_ratio"] = features["frac_integer"] + features["frac_binary"]
            attributions["binary_share_of_integers"] = float(binary_share)
            attributions["cut_score"] = float(cut_score)

        elif p_class == "QP":
            # Active set shines on small dense problems with few constraints; IPM scales and handles degeneracy.
            size = features["log_num_vars"] + features["log_num_cons"]
            score_active = -2.5 * (size - 1.6) + 0.5 * features["density"]
            prob_active = _sigmoid(score_active)
            algo_probs = {"qp_interior_point": 1.0 - prob_active, "active_set": prob_active}
            rec_algo = "active_set" if prob_active > 0.5 else "qp_interior_point"
            confidence = max(prob_active, 1.0 - prob_active)
            fallback = "qp_interior_point"
            attributions["quadratic_objective"] = 1.0
            attributions["problem_size_log10"] = float(size)

        else:
            # Linear Programming: Simplex (vertex, warm-startable) vs homogeneous IPM (large / dense)
            log_nnz = features["log_num_nnz"]
            density = features["density"]
            aspect = features["aspect_ratio"]
            cond = features["est_condition_log10"]
            score_ipm = (
                0.35 * (log_nnz - 3.0)
                + 0.40 * (density * 10.0)
                - 0.30 * abs(np.log10(aspect))
                + 0.15 * (cond - 3.0)
            )
            prob_ipm = _sigmoid(score_ipm)
            algo_probs = {"simplex": 1.0 - prob_ipm, "interior_point": prob_ipm}
            rec_algo = "simplex" if prob_ipm <= 0.5 else "interior_point"
            confidence = max(prob_ipm, 1.0 - prob_ipm)
            fallback = "dual_simplex"
            attributions["matrix_density"] = density
            attributions["problem_scale_nnz"] = log_nnz
            attributions["aspect_ratio"] = aspect
            attributions["condition_estimate"] = cond

            learned = _learned_lp_choice(features)
            if learned is not None:
                algo_probs, rec_algo, confidence = learned
                attributions["learned_selector"] = 1.0
            if model.num_variables > 250_000:
                # Factorization-based methods run out of time/memory here; first-order PDLP only needs SpMV.
                rec_algo, confidence = "pdlp", 0.9
                algo_probs = {**{k: 0.0 for k in algo_probs}, "pdlp": 1.0}
                attributions["very_large_lp"] = float(model.num_variables)

        raw_nnz = model.get_metadata().num_nonzeros
        if raw_nnz > 25000 and features["density"] > 0.02:
            hardware = "gpu"
            attributions["gpu_spmv_benefit"] = 0.82
        else:
            hardware = "cpu"
            attributions["cpu_low_latency_preferred"] = 0.91

        # Deterministic Safety Harness: below the confidence threshold use the proven fallback.
        if confidence < self.confidence_threshold:
            rec_algo = fallback
            confidence = 0.60

        return StrategyRecommendation(
            recommended_algorithm=rec_algo,
            algorithm_probabilities={k: float(v) for k, v in algo_probs.items()},
            confidence_score=float(confidence),
            recommended_hardware=hardware,
            branching_strategy=branching,
            feature_attributions=attributions,
            deterministic_fallback=fallback,
            cut_strategy=cut_strategy,
            heuristic_intensity=heuristic_intensity,
            relaxation_solver=relaxation,
        )
